name: Execute FF Engine Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  engine-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Advisor Engine Script
        run: python advisor_engine.py
